name: ui_eval_example
description: Example app for ui_eval - Type-safe UI DSL for Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  cupertino_icons: 1.0.6
  flutter:
    sdk: flutter
  ui_eval:
    path: ../

dev_dependencies:
  flutter_lints: 3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/apps/
    - assets/ts_logic/logic_bundle.js
